/* This file is not yet automatically regenerated by VisualGDB and can be edited manually. */

#pragma once
/* Number of interrupts allocated */
#ifndef VECTOR_DATA_IRQ_COUNT
#define VECTOR_DATA_IRQ_COUNT    (0)
#endif
/* ISR prototypes */

/* Vector table allocations */
