/* This file is not yet automatically regenerated by VisualGDB and can be edited manually. */
#ifndef BLINKY_THREAD_H_
#define BLINKY_THREAD_H_
#include "bsp_api.h"
#include "tx_api.h"
#include "hal_data.h"
#ifdef __cplusplus
                extern "C" void blinky_thread_entry(void);
                #else
extern void blinky_thread_entry(void);
#endif
FSP_HEADER
FSP_FOOTER
#endif /* BLINKY_THREAD_H_ */
